--------------------------------------------------------
--  File created - środa-czerwiec-04-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence POSTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HPH"."POSTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARDS
--------------------------------------------------------

  CREATE TABLE "HPH"."BOARDS" 
   (	"BOARD_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"PARENT_ID" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "HPH"."MENU" 
   (	"ITEM_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(48 BYTE), 
	"CONTROLLER" VARCHAR2(20 BYTE), 
	"ACTION" VARCHAR2(20 BYTE), 
	"PARENT_ID" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "HPH"."POSTS" 
   (	"POST_ID" NUMBER, 
	"BOARD_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"TOPIC" VARCHAR2(45 BYTE), 
	"DATETIME" NUMBER, 
	"REPLY_ID" NUMBER, 
	"CONTENT" CLOB, 
	"APPROVED" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "HPH" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "HPH"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"TOKEN" VARCHAR2(255 BYTE), 
	"LOGIN" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPH"."TABLE1_PK" ON "HPH"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPH"."MENU_PK" ON "HPH"."MENU" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Index BOARDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPH"."BOARDS_PK" ON "HPH"."BOARDS" ("BOARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  Constraints for Table BOARDS
--------------------------------------------------------

  ALTER TABLE "HPH"."BOARDS" ADD CONSTRAINT "BOARDS_PK" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH"  ENABLE;
  ALTER TABLE "HPH"."BOARDS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HPH"."BOARDS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "HPH"."POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HPH"."POSTS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "HPH"."POSTS" MODIFY ("POST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HPH"."USERS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH"  ENABLE;
  ALTER TABLE "HPH"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HPH"."USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "HPH"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HPH"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH"  ENABLE;
  ALTER TABLE "HPH"."MENU" MODIFY ("PARENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HPH"."MENU" MODIFY ("CONTROLLER" NOT NULL ENABLE);
  ALTER TABLE "HPH"."MENU" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HPH"."MENU" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HPH"."MENU" ADD CONSTRAINT "PARENT_ID" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "HPH"."MENU" ("ITEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSTS_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HPH"."POSTS_BIR" 
BEFORE INSERT ON posts 
FOR EACH ROW

BEGIN
  SELECT posts_seq.NEXTVAL
  INTO   :new.post_id
  FROM   dual;
END;
/
ALTER TRIGGER "HPH"."POSTS_BIR" ENABLE;
