--------------------------------------------------------
--  File created - niedziela-maj-25-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence POSTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HPH"."POSTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARDS
--------------------------------------------------------

  CREATE TABLE "HPH"."BOARDS" 
   (	"BOARD_ID" NUMBER, 
	"NAME" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"PARENT_ID" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "HPH"."POSTS" 
   (	"POST_ID" NUMBER, 
	"BOARD_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"TOPIC" VARCHAR2(45 BYTE), 
	"DATETIME" NUMBER, 
	"REPLY_ID" NUMBER, 
	"CONTENT" CLOB, 
	"APPROVED" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "HPH" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "HPH"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"TOKEN" VARCHAR2(255 BYTE), 
	"LOGIN" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
REM INSERTING into HPH.BOARDS
SET DEFINE OFF;
Insert into HPH.BOARDS (BOARD_ID,NAME,DESCRIPTION,PARENT_ID) values ('1','test board','test board 123','0');
REM INSERTING into HPH.POSTS
SET DEFINE OFF;
Insert into HPH.POSTS (POST_ID,BOARD_ID,USER_ID,TOPIC,DATETIME,REPLY_ID,APPROVED) values ('1','1','0','test','1312412','0','0');
Insert into HPH.POSTS (POST_ID,BOARD_ID,USER_ID,TOPIC,DATETIME,REPLY_ID,APPROVED) values ('1','1','0','dupa',null,null,'0');
Insert into HPH.POSTS (POST_ID,BOARD_ID,USER_ID,TOPIC,DATETIME,REPLY_ID,APPROVED) values ('2','1','1','test',null,null,'0');
REM INSERTING into HPH.USERS
SET DEFINE OFF;
Insert into HPH.USERS (USER_ID,EMAIL,TOKEN,LOGIN,PASSWORD) values ('1',null,'f4e4b6af8c2d1b0e2111b045201aebc3','admin','ca798b423b94fc52aca083f34fd7e394,24389bfe4fe2eba8bf9aa9203a44cdad');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPH"."TABLE1_PK" ON "HPH"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  DDL for Index BOARDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HPH"."BOARDS_PK" ON "HPH"."BOARDS" ("BOARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HPH"."USERS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH"  ENABLE;
  ALTER TABLE "HPH"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HPH"."USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "HPH"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARDS
--------------------------------------------------------

  ALTER TABLE "HPH"."BOARDS" ADD CONSTRAINT "BOARDS_PK" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPH"  ENABLE;
  ALTER TABLE "HPH"."BOARDS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HPH"."BOARDS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "HPH"."POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HPH"."POSTS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "HPH"."POSTS" MODIFY ("POST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger POSTS_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HPH"."POSTS_BIR" 
BEFORE INSERT ON posts 
FOR EACH ROW

BEGIN
  SELECT posts_seq.NEXTVAL
  INTO   :new.post_id
  FROM   dual;
END;
/
ALTER TRIGGER "HPH"."POSTS_BIR" ENABLE;
